import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header";

import { Roboto } from "next/font/google";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css"
        rel="stylesheet"
      />
      <body style={{ background: "#fff"}} className={roboto.className}>
        {/* <Header /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
